In [17]:
import pandas as pd
df = pd.read_csv('20220207.csv' , encoding='cp949')
df_2017 = df[df['연도'] == 2017]
df_2017.to_csv('2017.csv' ,encoding='cp949')

In [40]:
from sqlalchemy import create_engine , text
import os
from dotenv import load_dotenv
load_dotenv()

user_id = os.getenv('DB_USER')
user_pwd = os.getenv('DB_PASSWORD')
db_name = os.getenv('DB_NAME')

engine = create_engine(f'mysql+pymysql://{user_id}:{user_pwd}@localhost:3306/{db_name}')
conn = engine.connect()
result = conn.execute(text("select 1"))
print(result.fetchall())
conn.close()

#df = pd.read_sql('SELECT * FROM table_name', engine)

[(1,)]

In [38]:
pd.read_sql('select * from sale_car',engine)

    sale_car_id  year  month company  amount
0             1  2025      1      기아   38412
1             2  2025      1      현대   37230
2             3  2025      1    제네시스    8824
3             4  2025      1   르노코리아    2601
4             5  2025      1     KGM    2300
..          ...   ...    ...     ...     ...
67           68  2025     12      기아   44831
68           69  2025     12    제네시스    9680
69           70  2025     12   르노코리아    4771
70           71  2025     12     KGM    2659
71           72  2025     12     쉐보레    1126

[72 rows x 5 columns]

In [44]:
import pandas as pd
from glob import glob

file_path = 'data/*.csv'
files = glob(file_path)
print(files[8])
df = pd.read_csv(files[8])
df.head(5)

data\소상공인시장진흥공단_상가(상권)정보_서울_202512.csv

,상가업소번호,상호명,지점명,상권업종대분류코드,상권업종대분류명,상권업종중분류코드,상권업종중분류명,상권업종소분류코드,상권업종소분류명,표준산업분류코드,...,건물관리번호,건물명,도로명주소,구우편번호,신우편번호,동정보,층정보,호정보,경도,위도
0,MA010120220804265295,60계치킨암사,선사점,I2,음식,I210,기타 간이,I21006,치킨,I56193,...,1174010700105020004015779,암사동정웅빌딩,서울특별시 강동구 상암로3길 8,134877,5241,NaN,1,NaN,127.126859,37.550810
1,MA010120220809658173,성심인력공사,NaN,N1,시설관리·임대,N104,고용 알선,N10401,고용 알선업,N75110,...,1117010700100430059022991,NaN,서울특별시 용산구 한강대로 385,140821,4320,NaN,NaN,NaN,126.972240,37.552803
2,MA010120220808205276,칸토빈,NaN,I2,음식,I212,비알코올,I21201,카페,I56221,...,1150010800200200002002536,공항시장역,서울특별시 강서구 방화동로 30,157240,7619,NaN,1,NaN,126.810493,37.563548
3,MA010120220804370987,까치노래연습장,NaN,R1,예술·스포츠,R104,유원지·오락,R10407,노래방,R91223,...,1135010500101690179002482,NaN,서울특별시 노원구 한글비석로23길 2,139815,1682,NaN,NaN,NaN,127.071218,37.660715
4,MA010120220810170381,금빛주얼리,NaN,G2,소매,G217,시계·귀금속 소매,G21701,시계/귀금속 소매업,G47830,...,1111015100100880001000001,종로주얼리타운,서울특별시 종로구 돈화문로10길 2,110370,3138,NaN,1,NaN,126.991861,37.572331

In [ ]:
df2 = df.drop('상가업소번호',axis=1)
df2.columns

In [79]:
result = [ cname  for cname in df2.columns if '코드' in cname] + ['지번본번지',	'지번부번지',	'지번주소','건물관리번호']
result += ['도로명',	'건물본번지',	'건물부번지','건물명','구우편번호',	'신우편번호',	'동정보'	,'층정보',	'호정보']
df3 = df2.drop(result,axis=1)
df3.head(1)

,상호명,지점명,상권업종대분류명,상권업종중분류명,상권업종소분류명,표준산업분류명,시도명,시군구명,행정동명,법정동명,대지구분명,도로명주소,경도,위도
0,60계치킨암사,선사점,음식,기타 간이,치킨,치킨 전문점,서울특별시,강동구,암사2동,암사동,대지,서울특별시 강동구 상암로3길 8,127.126859,37.55081

In [ ]:
df3[df3['상권업종소분류명'] == '비디오방']

In [ ]:
df3.query('위도 > 37.4')

In [109]:
import numpy as np
import pandas as pd

data = {'age' : np.random.randint(0,100,50)}
df = pd.DataFrame(data)

df['label'] = pd.cut(df['age'],bins=4 , labels=['young','middle','old','oldest'])
df

    age   label
0    90  oldest
1    52     old
2    96  oldest
3    52     old
4     3   young
5    76  oldest
6    58     old
7    74     old
8    18   young
9    99  oldest
10   15   young
11    5   young
12   31  middle
13   33  middle
14    5   young
15    8   young
16    6   young
17   58     old
18   76  oldest
19    7   young
20    7   young
21   16   young
22   73     old
23   48  middle
24   65     old
25   63     old
26   74     old
27   11   young
28   49  middle
29   24   young
30   66     old
31   35  middle
32   54     old
33   82  oldest
34   40  middle
35   41  middle
36   24   young
37   45  middle
38   93  oldest
39   28  middle
40   67     old
41   83  oldest
42    6   young
43   80  oldest
44   81  oldest
45   95  oldest
46   50  middle
47   86  oldest
48   37  middle
49   16   young

In [ ]:
df['date'] = pd.date_range('2026-01-01', periods=150, freq='D')
dates = df['date'] = pd.to_datetime(df['date'])
df.index = dates
df.index.year

                 date
date
2026-01-01 2026-01-01
2026-01-02 2026-01-02
2026-01-03 2026-01-03
2026-01-04 2026-01-04
2026-01-05 2026-01-05
...               ...
2026-05-26 2026-05-26
2026-05-27 2026-05-27
2026-05-28 2026-05-28
2026-05-29 2026-05-29
2026-05-30 2026-05-30

[150 rows x 1 columns]